#!/bin/bash
# Clone upstream LK at a pinned commit, fetch ATfE, and apply the modloader overlay.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
LK_PIN="$(tr -d '[:space:]' < "$ROOT/LK_PIN")"
ATFE_VERSION="$(tr -d '[:space:]' < "$ROOT/ATFE_VERSION")"
LK_DIR="${LK_DIR:-$ROOT/build/lk}"
ATFE_ROOT="${ATFE_ROOT:-$ROOT/build/toolchain}"
ATFE_RELEASE="release-${ATFE_VERSION}-ATfE"
ATFE_BASE_URL="https://github.com/arm/arm-toolchain/releases/download/${ATFE_RELEASE}"

detect_atfe_platform() {
    local os arch
    os="$(uname -s)"
    arch="$(uname -m)"
    case "${os}-${arch}" in
        Linux-x86_64) echo "Linux-x86_64" ;;
        Linux-aarch64|Linux-arm64) echo "Linux-AArch64" ;;
        Darwin-arm64|Darwin-x86_64) echo "Darwin-universal" ;;
        *)
            echo "error: unsupported host ${os}-${arch} for ATfE auto-download" >&2
            exit 1
            ;;
    esac
}

atfe_archive_name() {
    local platform="$1"
    if [ "$platform" = "Darwin-universal" ]; then
        echo "ATfE-${ATFE_VERSION}-Darwin-universal.dmg"
    else
        echo "ATfE-${ATFE_VERSION}-${platform}.tar.xz"
    fi
}

verify_sha256() {
    local file="$1" checksum_file="$2"
    if [ ! -f "$checksum_file" ]; then
        echo "error: missing checksum file $checksum_file" >&2
        exit 1
    fi
    (
        cd "$(dirname "$file")"
        sha256sum -c "$(basename "$checksum_file")"
    )
}

download_atfe_archive() {
    local platform="$1" archive="$2" tarball="$3" checksum="$4"
    mkdir -p "$ATFE_ROOT"

    if [ -f "$tarball" ]; then
        echo "Using cached ATfE archive $tarball"
    else
        echo "Downloading ATfE ${ATFE_VERSION} (${platform}) from arm/arm-toolchain ..."
        curl -fSL --progress-bar -o "$checksum" "${ATFE_BASE_URL}/${archive}.sha256"
        curl -fSL --progress-bar -o "$tarball" "${ATFE_BASE_URL}/${archive}"
        echo ""
    fi

    if ! verify_sha256 "$tarball" "$checksum"; then
        echo "error: checksum verification failed for $tarball" >&2
        exit 1
    fi
}

extract_atfe() {
    local platform="$1" archive="$2" tarball="$3"
    local extract_dir="$ATFE_ROOT"

    if [ "$platform" = "Darwin-universal" ]; then
        echo "error: DMG install is not automated; mount ${tarball} and set ATFE_DIR" >&2
        exit 1
    fi

    echo "Extracting ATfE from $tarball ..."
    tar -xJf "$tarball" -C "$extract_dir"
}

ensure_atfe() {
    local platform archive tarball checksum atfe_dir

    platform="$(detect_atfe_platform)"
    archive="$(atfe_archive_name "$platform")"
    tarball="${ATFE_TARBALL:-$ATFE_ROOT/$archive}"
    checksum="${tarball}.sha256"
    atfe_dir="${ATFE_DIR:-$ATFE_ROOT/ATfE-${ATFE_VERSION}-${platform}}"

    if [ -x "$atfe_dir/bin/clang" ]; then
        ATFE_DIR="$atfe_dir"
        return 0
    fi

    if [ ! -f "$tarball" ] || [ ! -f "$checksum" ]; then
        download_atfe_archive "$platform" "$archive" "$tarball" "$checksum"
    elif ! verify_sha256 "$tarball" "$checksum"; then
        echo "Re-downloading ATfE archive (checksum mismatch) ..."
        rm -f "$tarball" "$checksum"
        download_atfe_archive "$platform" "$archive" "$tarball" "$checksum"
    fi

    extract_atfe "$platform" "$archive" "$tarball"

    if [ ! -x "$atfe_dir/bin/clang" ]; then
        echo "error: ATfE ${ATFE_VERSION} not found at $atfe_dir/bin/clang" >&2
        exit 1
    fi

    ATFE_DIR="$atfe_dir"
}

write_local_mk() {
    local local_mk="$LK_DIR/local.mk"
    cat > "$local_mk" <<EOF
# Generated by setup.sh — do not commit.
TOOLCHAIN := clang
LD := ld.lld
CLANG_BINDIR := ${ATFE_DIR}/bin
EOF
}

clone_lk() {
    if [ ! -d "$LK_DIR/.git" ]; then
        echo "Cloning littlekernel/lk into $LK_DIR ..."
        mkdir -p "$(dirname "$LK_DIR")"
        git clone https://github.com/littlekernel/lk.git "$LK_DIR"
    fi

    echo "Checking out LK pin $LK_PIN ..."
    git -C "$LK_DIR" fetch origin --tags
    git -C "$LK_DIR" checkout --force "$LK_PIN"
}

apply_overlay() {
    echo "Applying modloader overlay ..."
    mkdir -p "$LK_DIR/app" "$LK_DIR/project"
    rsync -a "$ROOT/app/modloader/" "$LK_DIR/app/modloader/"
    cp "$ROOT/project/modloader.mk" "$LK_DIR/project/modloader.mk"
    chmod +x "$LK_DIR/app/modloader/"*.sh
}

echo "==> [1/3] Ensuring ATfE toolchain ..."
ensure_atfe
echo "==> [2/3] Cloning/checking out upstream LK ..."
clone_lk
echo "==> [3/3] Applying modloader overlay ..."
apply_overlay
write_local_mk

echo ""
echo "ATfE ready:  $ATFE_DIR"
echo "LK tree ready: $LK_DIR"
echo "Build:  cd $LK_DIR && make modloader -j\$(nproc)"
echo "Test:   cd $LK_DIR && ./app/modloader/run_modtest_all.sh"
